# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 14:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.TextField(help_text='The dataset name for the selection')),
                ('query_string', models.TextField(blank=True, help_text='Query string for the data selection', max_length=2000, null=True)),
                ('metadata_oids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(help_text='Unique number for the observation metadata, usually in the form YYYYMMDDHHMMSS', verbose_name='Observation ID'), blank=True, help_text='List of metadata oids', null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of creation')),
                ('number_items', models.IntegerField(blank=True, help_text='Number of items in the data selection', null=True)),
            ],
            options={
                'db_table': 'data_selection',
            },
        ),
        migrations.CreateModel(
            name='UserDataSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the data selection', max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of creation')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date of last update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
                'db_table': 'user_data_selection',
                'get_latest_by': 'updated',
            },
        ),
        migrations.AddField(
            model_name='dataselection',
            name='user_data_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_selections', to='data_selection.UserDataSelection'),
        ),
        migrations.AlterUniqueTogether(
            name='userdataselection',
            unique_together=set([('user', 'name')]),
        ),
    ]
