/* Define constants global to the whole App */

const DEBUG = false;

/* The URL of the SVO API
All resources URI in the SVO API will be relative to that */
export const SVO_API_URL = DEBUG ? 'http://localhost:8800/' : 'https://solarnet.oma.be/';

/* The URL of the SVO API schema */
export const SVO_API_SCHEMA_URL = DEBUG ? '/api/svo' : '/service/api/svo';

/* The default timeout for SVO API requests */
export const SVO_API_TIMEOUT = 60000;

/* Options for the paginated metadata tables */
export const SVO_PAGINATION_OPTIONS = Object.freeze({
	DEFAULT_PAGESIZE: 10,
	MINIMUM_PAGESIZE: 10,
	MAXIMUM_PAGESIZE: 100
});

/* The URL of the HEK API */
export const HEK_API_URL = 'https://www.lmsal.com/hek/her/';

/* The default timeout for HEK API requests */
export const HEK_API_TIMEOUT = 15000;

/* Options for the for paginated event tables */
export const HEK_PAGINATION_OPTIONS = Object.freeze({
	DEFAULT_PAGESIZE: 10,
	MINIMUM_PAGESIZE: 10,
	MAXIMUM_PAGESIZE: 100
});

/* The minimum required search params for a search request to the HEK API to be successful */
export const HEK_EVENT_LIST_SEARCH_PARAMS = Object.freeze({
	cosec: 2, // ask for json
	cmd: 'search', // search command
	type: 'column',
	event_coordsys: 'helioprojective', //always specify wide coordinates, otherwise does not work
	x1: '-5000',
	x2: '5000',
	y1: '-5000',
	y2: '5000',
	return: 'event_type,event_starttime,event_endtime,kb_archivid,gs_thumburl,frm_name,frm_identifier', // limit the returned fields
	event_type: '**', // override to only select some event types
	event_starttime: new Date(Date.UTC(1975, 9, 1)).toISOString(), // The first HEK event is in september 1975
	event_endtime: new Date().toISOString()
});

/* The required search params for converting an avent ivorn (kb_archivid) to a URL with the details of the event */
export const HEK_EVENT_DETAIL_SEARCH_PARAMS = Object.freeze({
	cmd: 'view-voevent',
	ivorn: ''
});

/* Type of events and their user friendly equivalent */
export const HEK_EVENT_TYPE_NAMES = Object.freeze({
	AR: 'Active Region',
	CE: 'CME',
	CD: 'Coronal Dimming',
	CH: 'Coronal Hole',
	CW: 'Coronal Wave',
	FI: 'Filament',
	FE: 'Filament Eruption',
	FA: 'Filament Activation',
	FL: 'Flare',
	LP: 'Loop',
	OS: 'Oscillation',
	SS: 'Sunspot',
	EF: 'Emerging Flux',
	CJ: 'Coronal Jet',
	PG: 'Plage',
	OT: 'Other',
	NR: 'Nothing Reported',
	SG: 'Sigmoid',
	SP: 'Spray Surge',
	CR: 'Coronal Rain',
	CC: 'Coronal Cavity',
	ER: 'Eruption',
	TO: 'Topological Object'
});

/* Type of detection */
export const HEK_DETECTION_METHODS = Object.freeze(['', 'LMSAL SSW PFSS forecast', 'EGSO_SFC', 'HMI SHARP', 'Flare Detective - Trigger Module', 'SPoCA', 'SWPC', 'Sigmoid Sniffer', 'SMART', 'SWAMIS-EF', 'AAFDCC', 'CACTus', 'SSW Latest Events', 'CDAW_GopalswamyYashiroFreeland', 'EruptionPatrol', 'EruptionCharacterize', 'RHESSI Flare Catalog', 'Yohkoh Flare Catalogue', 'AI_Sunspot_Finder', 'Solar Jet Hunter', 'TRACE observer', 'Coronal Dimming Module', 'FILEAS', 'Human Annotation', 'AFINO', 'WHPI', 'PSP', 'nil'])

export const HEK_EVENT_ATTRIBUTES = Object.freeze([
	{
		"name": "event_probability",
		"type": "real",
		"searchable": true,
		"description": "Probability or Confidence Level that event occured (bet. 0 and 1)",
		"verbose_name": "Event Probability",
	},
	{
		"name": "event_importance",
		"type": "real",
		"searchable": true,
		"description": "Rating or importance of the event (between 0 and 1). Can be used by automated methods to denote a metric.",
		"verbose_name": "Event Importance",
	},
	{
		"name": "event_type",
		"type": "text",
		"searchable": false,
		"description": "Event Type (e.g. 'FL: Flare' or 'AR: ActiveRegion')",
		"verbose_name": "Event Type",
	},
	{
		"name": "kb_archivdate",
		"type": "text",
		"searchable": false,
		"description": "Date when VOEvent entry was imported into Knowledge Base",
		"verbose_name": "KB Archiv Date",
	},
	{
		"name": "kb_archivid",
		"type": "text",
		"searchable": false,
		"description": "Unique internal ID of VOEvent entry",
		"verbose_name": "KB Archiv ID",
	},
	{
		"name": "kb_archivist",
		"type": "text",
		"searchable": false,
		"description": "Name of Archivist (internal. user should leave blank)",
		"verbose_name": "KB Archivist",
	},
	{
		"name": "kb_archivurl",
		"type": "text",
		"searchable": false,
		"description": "URL of VOEvent entry (internal. user should leave blank)",
		"verbose_name": "KB Archiv URL",
	},
	{
		"name": "event_coordsys",
		"type": "text",
		"searchable": false,
		"description": "Coordinate system type (Choose between UTC-HGS-TOPO [Heliographics Stonyhurst]",
		"verbose_name": "Event Coord. Sys",
	},
	{
		"name": "event_coordunit",
		"type": "text",
		"searchable": false,
		"description": 'Units of coordinates (e.g. "deg, deg" for UTC-HGS-TOP0)',
		"verbose_name": "Event Coord. Unit",
	},
	{
		"name": "event_endtime",
		"type": "time (ISO 8601)",
		"searchable": false,
		"description": "Time when event ends (e.g. 2004-02-14T02:00:01)",
		"verbose_name": "Event End Time",
	},
	{
		"name": "event_starttime",
		"type": "time (ISO 8601)",
		"searchable": false,
		"description": "Time when event starts (e.g. 2004-02-14T02:00:01)",
		"verbose_name": "Event Start Time",
	},
	{
		"name": "event_expires",
		"type": "time (ISO 8601)",
		"searchable": false,
		"description": "Useful for reporting events before they are complete (e.g. 2004-02-14T02:00:01)",
		"verbose_name": "Event Expires",
	},
	{
		"name": "event_coord1",
		"type": "real",
		"searchable": true,
		"description": "Coordinate 1 of mean location of event",
		"verbose_name": "Event Coord1",
	},
	{
		"name": "event_coord2",
		"type": "real",
		"searchable": true,
		"description": "Coordinate 2 of mean location of event",
		"verbose_name": "Event Coord2",
	},
	{
		"name": "event_coord3",
		"type": "real",
		"searchable": true,
		"description": "Coordinate 3 of mean location of event (optional. Suitable for use with STEREO SECCHI events)",
		"verbose_name": "Event Coord3",
	},
	{
		"name": "event_mapurl",
		"type": "text",
		"searchable": false,
		"description": "URL to an image/intensity map",
		"verbose_name": "Event Map URL",
	},
	{
		"name": "event_maskurl",
		"type": "text",
		"searchable": false,
		"description": "URL to files which contain masks (e.g. binary masks) of region of interest.",
		"verbose_name": "Event Mask URL",
	},
	{
		"name": "event_peaktime",
		"type": "time (ISO 8601)",
		"searchable": false,
		"description": "Peak time of a flare (e.g. '2003-02-12T23:03:01')",
		"verbose_name": "Event Peak Time",
	},
	{
		"name": "event_c1error",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty in Coord1 of the mean location of the event.",
		"verbose_name": "Event C1 Error",
	},
	{
		"name": "event_c2error",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty in Coord2 of the mean location of the event.",
		"verbose_name": "Event C2 Error",
	},
	{
		"name": "event_clippedspatial",
		"type": "text",
		"searchable": false,
		"description": "Whether the spatial extent of the event is wholly contained within the data set ('T' or 'F').",
		"verbose_name": "Event Clipped Spatial",
	},
	{
		"name": "event_clippedtemporal",
		"type": "text",
		"searchable": false,
		"description": "Whether the temporal duration of the event is wholly contained within the data set ('T' or 'F').",
		"verbose_name": "Event Clipped Temporal",
	},
	{
		"name": "event_testflag",
		"type": "text",
		"searchable": false,
		"description": "A boolean flag to indicate that the event is for testing purposes ('T' or 'F')",
		"verbose_name": "Event Test Flag",
	},
	{
		"name": "event_description",
		"type": "text",
		"searchable": false,
		"description": "Description of the event",
		"verbose_name": "Event Description",
	},
	{
		"name": "frm_contact",
		"type": "text",
		"searchable": false,
		"description": "Contact information of Feature Recognition Method (FRM)",
		"verbose_name": "FRM Contact",
	},
	{
		"name": "frm_daterun",
		"type": "time (ISO 8601)",
		"searchable": false,
		"description": "Date when Feature Recognition Method (FRM) was run (e.g. 2004-02-15T02:00:01)",
		"verbose_name": "FRM Date Run",
	},
	{
		"name": "frm_humanflag",
		"type": "text",
		"searchable": false,
		"description": 'Whether a Human identified the event ("T" or "F")',
		"verbose_name": "FRM Human Flag",
	},
	{
		"name": "frm_identifier",
		"type": "text",
		"searchable": true,
		"description": "Username for Knowledge Base",
		"verbose_name": "FRM Identifier",
	},
	{
		"name": "frm_institute",
		"type": "text",
		"searchable": false,
		"description": "Institute where the Feature Recognition Method (FRM) orginates",
		"verbose_name": "FRM Institute",
	},
	{
		"name": "frm_name",
		"type": "text",
		"searchable": false,
		"description": 'Name of Feature Recognition Method (e.g. "Mark Cheung" or CACTUS")',
		"verbose_name": "FRM Name",
	},
	{
		"name": "frm_paramset",
		"type": "text",
		"searchable": false,
		"description": 'Values of parameters (e.g. "threshold=0.1")',
		"verbose_name": "FRM Param. Set",
	},
	{
		"name": "frm_versionnumber",
		"type": "real",
		"searchable": true,
		"description": "Version number of automated Feature Recognition Method (Put age if Human. Just kidding. In this case put 1.0)",
		"verbose_name": "FRM Version Number",
	},
	{
		"name": "frm_url",
		"type": "text",
		"searchable": false,
		"description": "URL to webpage containing information about the Feature Recognition Method",
		"verbose_name": "FRM URL",
	},
	{
		"name": "frm_specificid",
		"type": "text",
		"searchable": true,
		"description": "The specific ID of this event/feature assigned by the Feature Recognition Method",
		"verbose_name": "FRM Specific ID",
	},
	{
		"name": "obs_observatory",
		"type": "text",
		"searchable": false,
		"description": "Name of Observatory (e.g. SOHO)",
		"verbose_name": "OBS Observatory",
	},
	{
		"name": "obs_channelid",
		"type": "text",
		"searchable": false,
		"description": 'Name of Channel of the instrument (e.g. "G band")',
		"verbose_name": "OBS Channel ID",
	},
	{
		"name": "obs_instrument",
		"type": "text",
		"searchable": true,
		"description": 'Name of Instrument (e.g. "SOT")',
		"verbose_name": "OBS Instrument",
	},
	{
		"name": "obs_meanwavel",
		"type": "real",
		"searchable": true,
		"description": "Mean wavelength (preferably in Angstroms)",
		"verbose_name": "OBS Mean Wavelength",
	},
	{
		"name": "obs_wavelunit",
		"type": "text",
		"searchable": false,
		"description": 'Unit of OBS_MeanWavel (preferably "Angstroms")',
		"verbose_name": "OBS Wavelength Unit",
	},
	{
		"name": "obs_title",
		"type": "text",
		"searchable": true,
		"description": "Observational title",
		"verbose_name": "OBS Title",
	},
	{
		"name": "bound_ccnsteps",
		"type": "integer",
		"searchable": false,
		"description": "Number of steps in bounding chain code (useful for coronal hole boundaries)",
		"verbose_name": "Bound CC. number steps",
	},
	{
		"name": "bound_ccstartc1",
		"type": "real",
		"searchable": false,
		"description": "Beginning Coord1 of chain code",
		"verbose_name": "Bound CC. Start C1",
	},
	{
		"name": "bound_ccstartc2",
		"type": "real",
		"searchable": false,
		"description": "Beginning Coord2 of chain code",
		"verbose_name": "Bound CC. Start C2",
	},
	{
		"name": "bound_chaincode",
		"type": "text",
		"searchable": false,
		"description": "List of vertices for polygon (ordered list delimited by commas. e.g. 'x1, y1, x2, y2, x3, y3, x1, y1')",
		"verbose_name": "Bound Chain Code",
	},
	{
		"name": "boundbox_c1ll",
		"type": "real",
		"searchable": true,
		"description": "Coord1 of lower-left corner of bounding box",
		"verbose_name": "Bound Box C1 LL.",
	},
	{
		"name": "boundbox_c2ll",
		"type": "real",
		"searchable": true,
		"description": "Coord2 of lower-left corner of bounding box",
		"verbose_name": "Bound Box C2 LL.",
	},
	{
		"name": "boundbox_c1ur",
		"type": "real",
		"searchable": true,
		"description": "Coord1 of upper-right corner of bounding box",
		"verbose_name": "Bound Box C1 UR.",
	},
	{
		"name": "boundbox_c2ur",
		"type": "real",
		"searchable": true,
		"description": "Coord2 of upper-right corner of bounding box",
		"verbose_name": "Bound Box C2 UR.",
	},
	{
		"name": "chaincodetype",
		"type": "text",
		"searchable": false,
		"description": 'Type of chain code (Use "ordered list")',
		"verbose_name": "Chain Code Type",
	},
	{
		"name": "rasterscan",
		"type": "text",
		"searchable": true,
		"description": "Field for ascii string of raster scan",
		"verbose_name": "Raster Scan",
	},
	{
		"name": "rasterscantype",
		"type": "text",
		"searchable": true,
		"description": 'Type of raster scan (E.g. "EGSO_SFC" if you are using the EGSO Solar Feature Catalogue convection for the raster scan)',
		"verbose_name": "Raster Scan Type",
	},
	{
		"name": "skel_chaincode",
		"type": "text",
		"searchable": false,
		"description": "Skeleton code. A skeleton code is like a chain code except it isn't closed. (ordered list delimited by commas. e.g. 'x1, y1, x2, y2, x3, y3')",
		"verbose_name": "Skel. Chain Code",
	},
	{
		"name": "skel_curvature",
		"type": "real",
		"searchable": false,
		"description": "Curvature of skeleton",
		"verbose_name": "Skel. Curvature",
	},
	{
		"name": "skel_nsteps",
		"type": "integer",
		"searchable": false,
		"description": "Number of steps in skeleton",
		"verbose_name": "Skel. N. steps",
	},
	{
		"name": "skel_startc1",
		"type": "real",
		"searchable": false,
		"description": "Beginning Coord 1 of skeleton",
		"verbose_name": "Skel. Start C1",
	},
	{
		"name": "skel_startc2",
		"type": "real",
		"searchable": false,
		"description": "Beginning Coord 2 of skeleton",
		"verbose_name": "Skel. Start C2",
	},
	{
		"name": "ar_mcintoshcls",
		"type": "text",
		"searchable": true,
		"description": "Active Region McIntosh class",
		"verbose_name": "AR McIntosh Class",
	},
	{
		"name": "ar_mtwilsoncls",
		"type": "text",
		"searchable": true,
		"description": "Active Region Mt Wilson class",
		"verbose_name": "AR Mt Wilson Class",
	},
	{
		"name": "ar_zurichcls",
		"type": "text",
		"searchable": true,
		"description": "Active Region Zurich class",
		"verbose_name": "AR Zurich Class",
	},
	{
		"name": "ar_penumbracls",
		"type": "text",
		"searchable": true,
		"description": "Active Region Penumbra class",
		"verbose_name": "AR Penumbra Class",
	},
	{
		"name": "ar_compactnesscls",
		"type": "text",
		"searchable": true,
		"description": "Active Region Compactness class",
		"verbose_name": "AR Compactness Class",
	},
	{
		"name": "ar_noaaclass",
		"type": "text",
		"searchable": true,
		"description": "Active Regon NOAA class",
		"verbose_name": "AR NOAA Class",
	},
	{
		"name": "ar_noaanum",
		"type": "integer",
		"searchable": true,
		"description": "NOAA designated Active Region Number (e.g. 10930)",
		"verbose_name": "AR NOAA Number",
	},
	{
		"name": "ar_numspots",
		"type": "integer",
		"searchable": true,
		"description": "Number of spots in Active region",
		"verbose_name": "AR N. Spots",
	},
	{
		"name": "ar_polarity",
		"type": "integer",
		"searchable": true,
		"description": "Polarity of Active region ('1' or '-1' for positive and negative respectively)",
		"verbose_name": "AR Polarity",
	},
	{
		"name": "ar_spotarearaw",
		"type": "real",
		"searchable": true,
		"description": "Area of spots in active region in plane of sky",
		"verbose_name": "AR Spot Area Raw",
	},
	{
		"name": "ar_spotarearawuncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of AR_SpotAreaRaw",
		"verbose_name": "AR Spot Area Raw Uncert.",
	},
	{
		"name": "ar_spotarearawunit",
		"type": "text",
		"searchable": false,
		"description": "Units of AR_SpotAreaRaw",
		"verbose_name": "AR Spot Area Raw Unit",
	},
	{
		"name": "ar_spotarearepr",
		"type": "real",
		"searchable": true,
		"description": "Reprojected area of spots in heliographic units",
		"verbose_name": "AR Spot Area Repr.",
	},
	{
		"name": "ar_spotarearepruncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty Reprojected area of spots in heliographic units",
		"verbose_name": "AR Spot Area Repr. Uncert",
	},
	{
		"name": "ar_spotareareprunit",
		"type": "text",
		"searchable": false,
		"description": "Units of AR_SpotAreaReprUnit (e.g. 'millihemispheres' or 'steradians')",
		"verbose_name": "AR Spot Area Repr. Unit",
	},
	{
		"name": "sharp_noaa_ars",
		"type": "text",
		"searchable": true,
		"description": "Comma separated list of NOAA_ARS within lat/lon bounding box. Can include ones without NOAA# at time of event.",
		"verbose_name": "SHARP NOAA ARS",
	},
	{
		"name": "intensmin",
		"type": "real",
		"searchable": true,
		"description": "Minimum intensity of pixels",
		"verbose_name": "Intens. Min",
	},
	{
		"name": "intensmax",
		"type": "real",
		"searchable": true,
		"description": "Maximum intensity of pixels",
		"verbose_name": "Intens. Max",
	},
	{
		"name": "intensmean",
		"type": "real",
		"searchable": true,
		"description": "Mean intensity of pixels",
		"verbose_name": "Intens. Mean",
	},
	{
		"name": "intensmedian",
		"type": "real",
		"searchable": true,
		"description": "Mdian intensity of pixels",
		"verbose_name": "Intens. Median",
	},
	{
		"name": "intensvar",
		"type": "real",
		"searchable": true,
		"description": "Variance of intensity of pixels",
		"verbose_name": "Intens. Var",
	},
	{
		"name": "intensskew",
		"type": "real",
		"searchable": true,
		"description": "Skewness of intensity of pixels",
		"verbose_name": "Intens. Skew",
	},
	{
		"name": "intenskurt",
		"type": "real",
		"searchable": true,
		"description": "Kurtosis of intensity of pixels",
		"verbose_name": "Intens. Kurt",
	},
	{
		"name": "intenstotal",
		"type": "real",
		"searchable": true,
		"description": "Sum of intensities of pixels",
		"verbose_name": "Intens. Total",
	},
	{
		"name": "intensunit",
		"type": "text",
		"searchable": false,
		"description": "Units of intensity",
		"verbose_name": "Intens. Unit",
	},
	{
		"name": "fl_goescls",
		"type": "text",
		"searchable": true,
		"description": "GOES Flare class (e.g. 'X11')",
		"verbose_name": "FL GOES Class",
	},
	{
		"name": "cme_radiallinvel",
		"type": "real",
		"searchable": true,
		"description": "Radial Linear fit radial velocity of CME",
		"verbose_name": "CME Radial Lin. Velocity",
	},
	{
		"name": "cme_radiallinveluncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty in CME_RadialLinVel",
		"verbose_name": "CME Radial Lin. Velocity Uncert",
	},
	{
		"name": "cme_radiallinvelmin",
		"type": "real",
		"searchable": true,
		"description": "Mininum linear radial velocity of CME",
		"verbose_name": "CME Radial Lin. Velocity Min",
	},
	{
		"name": "cme_radiallinvelmax",
		"type": "real",
		"searchable": true,
		"description": "Maximum linear radial velocity of CME",
		"verbose_name": "CME Radial Lin. Velocity Max",
	},
	{
		"name": "cme_radiallinvelstddev",
		"type": "real",
		"searchable": true,
		"description": "Standard Deviation of radial velocity of CME",
		"verbose_name": "CME Radial Lin. Velocity Stddev",
	},
	{
		"name": "cme_radiallinvelunit",
		"type": "text",
		"searchable": false,
		"description": "Units for Radial velocity of CME (e.g. 'km/s')",
		"verbose_name": "CME Radial Lin. Velocity Unit",
	},
	{
		"name": "cme_angularwidth",
		"type": "real",
		"searchable": true,
		"description": "Angular width of CME",
		"verbose_name": "CME Angular Width",
	},
	{
		"name": "cme_angularwidthunit",
		"type": "text",
		"searchable": false,
		"description": "Units for angular width of CME (e.g. 'deg')",
		"verbose_name": "CME Angular Width Unit",
	},
	{
		"name": "cme_accel",
		"type": "real",
		"searchable": true,
		"description": "Acceleration of CME",
		"verbose_name": "CME Accel",
	},
	{
		"name": "cme_acceluncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of CME acceleration",
		"verbose_name": "CME Accel Uncert.",
	},
	{
		"name": "cme_accelunit",
		"type": "text",
		"searchable": false,
		"description": "Units for CME acceleration (e.g. 'km/s/s')",
		"verbose_name": "CME Accel Unit",
	},
	{
		"name": "cme_mass",
		"type": "real",
		"searchable": true,
		"description": "Mass contained in CME (e.g. '1e17')",
		"verbose_name": "CME Mass",
	},
	{
		"name": "cme_massuncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty in mass contained in cme",
		"verbose_name": "CME Mass Uncert.",
	},
	{
		"name": "cme_massunit",
		"type": "text",
		"searchable": false,
		"description": "Units for CME mass (e.g. 'g')",
		"verbose_name": "CME Mass Unit",
	},
	{
		"name": "area_atdiskcenter",
		"type": "real",
		"searchable": true,
		"description": "Area of event at disk center",
		"verbose_name": "Area At Disk Center",
	},
	{
		"name": "area_atdiskcenteruncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of area at disk center",
		"verbose_name": "Area At Disk Center Uncert.",
	},
	{
		"name": "area_raw",
		"type": "real",
		"searchable": true,
		"description": "Area of event in sky plane",
		"verbose_name": "Area Raw",
	},
	{
		"name": "area_uncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of area in sky plane",
		"verbose_name": "Area Uncert.",
	},
	{
		"name": "area_unit",
		"type": "text",
		"searchable": false,
		"description": "Units of area in sky plane (e.g. 'arcsec2')",
		"verbose_name": "Area Unit",
	},
	{
		"name": "event_npixels",
		"type": "integer",
		"searchable": true,
		"description": "Number of pixels pertaining to event",
		"verbose_name": "Event N. pixels",
	},
	{
		"name": "event_pixelunit",
		"type": "text",
		"searchable": false,
		"description": "Units of values given in pixels",
		"verbose_name": "Event Pixel Unit",
	},
	{
		"name": "freqmaxrange",
		"type": "real",
		"searchable": true,
		"description": "Maximum of the frequency range of oscillation",
		"verbose_name": "Freq Max Range",
	},
	{
		"name": "freqminrange",
		"type": "real",
		"searchable": true,
		"description": "Minimum of the frequency range of oscillation",
		"verbose_name": "Freq Min Range",
	},
	{
		"name": "freqpeakpower",
		"type": "real",
		"searchable": true,
		"description": "Frequency at which power spectrum peaks",
		"verbose_name": "Freq Peak Power",
	},
	{
		"name": "frequnit",
		"type": "text",
		"searchable": false,
		"description": "Units of frequency (e.g. 'Hz')",
		"verbose_name": "Freq. Unit",
	},
	{
		"name": "intensmaxampl",
		"type": "real",
		"searchable": true,
		"description": "Maximum amplitude of oscillation in intensity signal",
		"verbose_name": "Intens. Max Ampl.",
	},
	{
		"name": "intensminampl",
		"type": "real",
		"searchable": true,
		"description": "Minimum amplitude of oscillation in intensity signal",
		"verbose_name": "Intens. Min Ampl.",
	},
	{
		"name": "oscillnperiods",
		"type": "real",
		"searchable": true,
		"description": "Number of periods detected in oscillation",
		"verbose_name": "Oscill N. Periods",
	},
	{
		"name": "oscillnperiodsuncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of number of periods detected in oscillation",
		"verbose_name": "Oscill N. Periods Uncert.",
	},
	{
		"name": "peakpower",
		"type": "real",
		"searchable": true,
		"description": "Peak power of oscillation",
		"verbose_name": "Peak Power",
	},
	{
		"name": "peakpowerunit",
		"type": "text",
		"searchable": false,
		"description": "Units of peak power of oscillation",
		"verbose_name": "Peak Power Unit",
	},
	{
		"name": "velocmaxampl",
		"type": "real",
		"searchable": true,
		"description": "Maximum amplitude of oscillation in velocity signal (e.g. doppler signal)",
		"verbose_name": "Velocity Max Ampl.",
	},
	{
		"name": "velocmaxpower",
		"type": "real",
		"searchable": true,
		"description": "Maximum power of oscillation in velocity signal",
		"verbose_name": "Velocity Max Power",
	},
	{
		"name": "velocmaxpoweruncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty in max power in velocity signal",
		"verbose_name": "Velocity Max Power Uncert.",
	},
	{
		"name": "velocminampl",
		"type": "real",
		"searchable": true,
		"description": "Minimum amplitude in oscillating velocity signal",
		"verbose_name": "Velocity Min Ampl.",
	},
	{
		"name": "velocunit",
		"type": "text",
		"searchable": false,
		"description": "Units for velocity (e.g. 'km/s')",
		"verbose_name": "Velocity Unit",
	},
	{
		"name": "wavedisplmaxampl",
		"type": "real",
		"searchable": true,
		"description": "Maximum amplitude of oscillation in displacement signal",
		"verbose_name": "Wave Displacement Max Ampl.",
	},
	{
		"name": "wavedisplminampl",
		"type": "real",
		"searchable": true,
		"description": "Minimum amplitude of oscillatoin in displacement signal",
		"verbose_name": "Wave Displacement Min Ampl",
	},
	{
		"name": "wavedisplunit",
		"type": "text",
		"searchable": false,
		"description": "Units for displacement amplitude (e.g. 'arcsec')",
		"verbose_name": "Wave Displacement Unit",
	},
	{
		"name": "wavelmaxpower",
		"type": "real",
		"searchable": true,
		"description": "Wavelength at which spatial power spectrum peaks",
		"verbose_name": "Wavelength Max Power",
	},
	{
		"name": "wavelmaxpoweruncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of WavelMaxPower",
		"verbose_name": "Wavelength Max Power Uncert.",
	},
	{
		"name": "wavelmaxrange",
		"type": "real",
		"searchable": true,
		"description": "Maximum wavelength of wavelength range for spatial oscillation",
		"verbose_name": "Wavelength Max Range",
	},
	{
		"name": "wavelminrange",
		"type": "real",
		"searchable": true,
		"description": "Minimum wavelength of wavelength range for spatial oscillation",
		"verbose_name": "Wavelength Min Range",
	},
	{
		"name": "wavelunit",
		"type": "text",
		"searchable": false,
		"description": "Units for spatial oscillation wavelength (e.g. 'km')",
		"verbose_name": "Wavelength Unit",
	},
	{
		"name": "ef_pospeakfluxonsetrate",
		"type": "real",
		"searchable": true,
		"description": "Emergence rate of positive polarity flux",
		"verbose_name": "EF Pos. Peak Flux Onset Rate",
	},
	{
		"name": "ef_negpeakfluxonsetrate",
		"type": "real",
		"searchable": true,
		"description": "Emergence rate of negative polarity flux",
		"verbose_name": "EF Neg. Peak Flux Onset Rate",
	},
	{
		"name": "ef_onsetrateunit",
		"type": "text",
		"searchable": false,
		"description": "Emergence rate unit (e.g. 'Mx/s')",
		"verbose_name": "EF Onset Rate Unit",
	},
	{
		"name": "ef_sumpossignedflux",
		"type": "real",
		"searchable": true,
		"description": "Total positive signed flux at completion",
		"verbose_name": "EF Sum Pos. Signed Flux",
	},
	{
		"name": "ef_sumnegsignedflux",
		"type": "real",
		"searchable": true,
		"description": "Total negative signed flux at completion (negative number)",
		"verbose_name": "EF Sum Neg. Signed Flux",
	},
	{
		"name": "ef_fluxunit",
		"type": "text",
		"searchable": false,
		"description": "Flux unit (e.g. 'Mx')",
		"verbose_name": "EF Flux Unit",
	},
	{
		"name": "ef_axisorientation",
		"type": "real",
		"searchable": false,
		"description": "Axis orientation of emerging flux pair (CCW from parallels in Stonyhurst longitude",
		"verbose_name": "EF Axis Orientation",
	},
	{
		"name": "ef_axisorientationunit",
		"type": "text",
		"searchable": false,
		"description": "Axis oriention unit (deg)",
		"verbose_name": "EF Axis Orientation Unit",
	},
	{
		"name": "ef_axislength",
		"type": "real",
		"searchable": false,
		"description": "Axis length of emerging flux pair at completion",
		"verbose_name": "EF Axis Length",
	},
	{
		"name": "ef_posequivradius",
		"type": "real",
		"searchable": false,
		"description": "Equivalent radius (i.e. sqrt(area/pi) of positive polarity at completion",
		"verbose_name": "EF Pos. Equiv Radius",
	},
	{
		"name": "ef_negequivradius",
		"type": "real",
		"searchable": false,
		"description": "Equivalent radius (i.e. sqrt(area/pi) of negative polarity at completion",
		"verbose_name": "EF Neg. Equiv Radius",
	},
	{
		"name": "ef_lengthunit",
		"type": "text",
		"searchable": false,
		"description": "Units for EF_AxisLength",
		"verbose_name": "EF Length Unit",
	},
	{
		"name": "ef_aspectratio",
		"type": "real",
		"searchable": false,
		"description": "(EF_PosEquivRadius+EF_NegEquivRadius)/(2*EF_AxisLength)",
		"verbose_name": "EF Aspect Ratio",
	},
	{
		"name": "ef_proximityratio",
		"type": "real",
		"searchable": false,
		"description": "(EF_PosEquivRadius-EF_NegEquivRadius)/(2*EF_AxisLength)",
		"verbose_name": "EF Proximity Ratio",
	},
	{
		"name": "maxmagfieldstrength",
		"type": "real",
		"searchable": true,
		"description": "Maximum magnetic field strength",
		"verbose_name": "Max Mag. Field Strength",
	},
	{
		"name": "maxmagfieldstrengthunit",
		"type": "text",
		"searchable": false,
		"description": "Units for maximum magnetic field strength (e.g. 'G' or 'Mx/cm2')",
		"verbose_name": "Max Mag. Field Strength Unit",
	},
	{
		"name": "outflow_length",
		"type": "real",
		"searchable": true,
		"description": "Length of outflow (can be for CoronalJet or SpraySurge)",
		"verbose_name": "Outflow Length",
	},
	{
		"name": "outflow_lengthunit",
		"type": "text",
		"searchable": false,
		"description": "Units for length of outflow (e.g. 'arcsec')",
		"verbose_name": "Outflow Length Unit",
	},
	{
		"name": "outflow_width",
		"type": "real",
		"searchable": true,
		"description": "Width of outflow",
		"verbose_name": "Outflow Width",
	},
	{
		"name": "outflow_widthunit",
		"type": "text",
		"searchable": false,
		"description": "Units for width of outflow (e.g. 'arcsec')",
		"verbose_name": "Outflow Width Unit",
	},
	{
		"name": "outflow_speed",
		"type": "real",
		"searchable": true,
		"description": "Outflow speed of outflow",
		"verbose_name": "Outflow Speed",
	},
	{
		"name": "outflow_transspeed",
		"type": "real",
		"searchable": true,
		"description": "Transverse speed relative to outflow direction",
		"verbose_name": "Outflow Trans. Speed",
	},
	{
		"name": "outflow_speedunit",
		"type": "text",
		"searchable": false,
		"description": "Units for speed (e.g. 'km/s')",
		"verbose_name": "Outflow Speed Unit",
	},
	{
		"name": "outflow_openingangle",
		"type": "real",
		"searchable": true,
		"description": "Opening angle of outflow (in degrees)",
		"verbose_name": "Outflow Opening Angle",
	},
	{
		"name": "obs_dataprepurl",
		"type": "text",
		"searchable": false,
		"description": "URL pointing to information about how data was reduced",
		"verbose_name": "OBS Data Prep. URL",
	},
	{
		"name": "fl_peakflux",
		"type": "real",
		"searchable": true,
		"description": "Flux at peak time",
		"verbose_name": "FL Peak Flux",
	},
	{
		"name": "fl_peakfluxunit",
		"type": "text",
		"searchable": false,
		"description": "Peak flux unit (e.g. erg/cm^2/s)",
		"verbose_name": "FL Peak Flux Unit",
	},
	{
		"name": "fl_peaktemp",
		"type": "real",
		"searchable": true,
		"description": "Temperature at peak time",
		"verbose_name": "FL Peak Temp.",
	},
	{
		"name": "fl_peaktempunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for FL_PeakTemp (K)",
		"verbose_name": "FL Peak Temp. Unit",
	},
	{
		"name": "fl_peakem",
		"type": "real",
		"searchable": true,
		"description": "Emission measure at peak time",
		"verbose_name": "FL Peak EM",
	},
	{
		"name": "fl_peakemunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for FL_PeakEM",
		"verbose_name": "FL Peak EM Unit",
	},
	{
		"name": "fl_efoldtime",
		"type": "real",
		"searchable": false,
		"description": "Flare e-folding time",
		"verbose_name": "FL E-Fold Time",
	},
	{
		"name": "fl_efoldtimeunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for FL_EFoldTime (s)",
		"verbose_name": "FL E-Fold Time Unit",
	},
	{
		"name": "fl_fluence",
		"type": "real",
		"searchable": true,
		"description": "Fluence of flare",
		"verbose_name": "FL Fluence",
	},
	{
		"name": "fl_fluenceunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for FL_Fluence (e.g. erg/cm^2)",
		"verbose_name": "FL Fluence Unit",
	},
	{
		"name": "fl_halphaclass",
		"type": "text",
		"searchable": true,
		"description": "H Alpha classification (used on some Yohkoh HXT)",
		"verbose_name": "FL Halpha Class",
	},
	{
		"name": "cd_area",
		"type": "real",
		"searchable": true,
		"description": "Maximum area of dimming",
		"verbose_name": "CD Area",
	},
	{
		"name": "cd_areauncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of CD_Area",
		"verbose_name": "CD Area Uncert.",
	},
	{
		"name": "cd_areaunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for CD_Area ('millihemisphere' or 'steradians')'",
		"verbose_name": "CD Area Unit",
	},
	{
		"name": "cd_volume",
		"type": "real",
		"searchable": true,
		"description": "Volume of dimming region",
		"verbose_name": "CD Volume",
	},
	{
		"name": "cd_volumeuncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty of CD_Volume",
		"verbose_name": "CD Volume Uncert.",
	},
	{
		"name": "cd_volumeunit",
		"type": "text",
		"searchable": false,
		"description": "Units for CD_Volume (e.g. 'cm^3')",
		"verbose_name": "CD Volume Unit",
	},
	{
		"name": "cd_mass",
		"type": "real",
		"searchable": true,
		"description": "Mass estimate calculated for dimming event",
		"verbose_name": "CD Mass",
	},
	{
		"name": "cd_massuncert",
		"type": "real",
		"searchable": false,
		"description": "Uncertainty for CD_Mass",
		"verbose_name": "CD Mass Uncert",
	},
	{
		"name": "cd_massunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for CD_Mass",
		"verbose_name": "CD Mass Unit",
	},
	{
		"name": "fi_length",
		"type": "real",
		"searchable": true,
		"description": "Length of Filament spine",
		"verbose_name": "FI Length",
	},
	{
		"name": "fi_lengthunit",
		"type": "text",
		"searchable": false,
		"description": "Unit for FI_Length",
		"verbose_name": "FI Length Unit",
	},
	{
		"name": "fi_tilt",
		"type": "real",
		"searchable": true,
		"description": "Mean tilt angle (in degrees) of the Filament spine (given as Skel_ChainCode) w.r. to solar equator",
		"verbose_name": "FI Tilt",
	},
	{
		"name": "fi_barbstot",
		"type": "integer",
		"searchable": true,
		"description": "Total number of filament barbs",
		"verbose_name": "FI Barbs Total",
	},
	{
		"name": "fi_barbsr",
		"type": "integer",
		"searchable": true,
		"description": "Total number of Right Bearing Barbs",
		"verbose_name": "FI Barbs Right",
	},
	{
		"name": "fi_barbsl",
		"type": "integer",
		"searchable": true,
		"description": "Total number of Left Bearing Barbs",
		"verbose_name": "FI Barbs Left",
	},
	{
		"name": "fi_chirality",
		"type": "integer",
		"searchable": true,
		"description": "Chirality for filament (-1 for sinistral",
		"verbose_name": "FI Chirality",
	},
	{
		"name": "fi_barbsstartc1",
		"type": "text",
		"searchable": false,
		"description": "List of Coord 1 of beginnings (closest to spine) of barbs (list delimited by commas for each numbered barb. e.g. 'x1, x2, x3')",
		"verbose_name": "FI Barbs Start C1",
	},
	{
		"name": "fi_barbsstartc2",
		"type": "text",
		"searchable": false,
		"description": "List of Coord 2 of beginnings (closest to spine) of barbs (list delimited by commas for each numbered barb. e.g. 'y1, y2, y3')",
		"verbose_name": "FI Barbs Start C2",
	},
	{
		"name": "fi_barbsendc1",
		"type": "text",
		"searchable": false,
		"description": "List of Coord 1 of ends of barbs (list delimited by commas for each numbered barb. e.g. 'x1, x2, x3')",
		"verbose_name": "FI Barbs End C1",
	},
	{
		"name": "fi_barbsendc2",
		"type": "text",
		"searchable": false,
		"description": "List of Coord 2 of ends of barbs (list delimited by commas for each numbered barb. e.g. 'y1, y2, y3')",
		"verbose_name": "FI Barbs End C2",
	},
	{
		"name": "sg_shape",
		"type": "text",
		"searchable": true,
		"description": "Shape of sigmoid",
		"verbose_name": "SG Shape",
	},
	{
		"name": "sg_chirality",
		"type": "integer",
		"searchable": true,
		"description": "Chirality of sigmoid (-1 for sinistral",
		"verbose_name": "SG Chirality",
	},
	{
		"name": "sg_orientation",
		"type": "real",
		"searchable": true,
		"description": "Angular rotation (ccw in degrees) of the main axis of the sigmoid to the active region",
		"verbose_name": "SG Orientation",
	},
	{
		"name": "sg_aspectratio",
		"type": "real",
		"searchable": false,
		"description": "TBD",
		"verbose_name": "SG Aspect Ratio",
	},
	{
		"name": "sg_peakcontrast",
		"type": "real",
		"searchable": false,
		"description": "TBD",
		"verbose_name": "SG Peak Contrast",
	},
	{
		"name": "sg_meancontrast",
		"type": "real",
		"searchable": false,
		"description": "TBD",
		"verbose_name": "SG Mean Contrast",
	},
	{
		"name": "obs_firstprocessingdate",
		"type": "text",
		"searchable": false,
		"description": "Earliest date of all images considered part of the event",
		"verbose_name": "OBS First Processing Date",
	},
	{
		"name": "obs_lastprocessingdate",
		"type": "text",
		"searchable": false,
		"description": "Latest date of all images considered part of the event",
		"verbose_name": "OBS Last Processing Date",
	},
	{
		"name": "obs_levelnum",
		"type": "real",
		"searchable": false,
		"description": "Level of Data (e.g. 1.5) = LVL_NUM",
		"verbose_name": "OBS Level Num.",
	},
	{
		"name": "obs_includesnrt",
		"type": "text",
		"searchable": false,
		"description": '"T" if any image in the event has the NRT flag (bit 30 in QUALITY), "F" otherwise',
		"verbose_name": "OBS Includes NRT",
	},
	{
		"name": "ss_spinrate",
		"type": "real",
		"searchable": true,
		"description": "Spin/Rotation rate of sunspots",
		"verbose_name": "SS Spin Rate",
	},
	{
		"name": "ss_spinrateunit",
		"type": "text",
		"searchable": false,
		"description": "Unit Spin/Rotation rate of sunspots (e.g. Deg/day)",
		"verbose_name": "SS Spin Rate Unit",
	},
	{
		"name": "cc_majoraxis",
		"type": "real",
		"searchable": false,
		"description": "Length of major axis of elliptical fit to cavity",
		"verbose_name": "CC Major Axis",
	},
	{
		"name": "cc_minoraxis",
		"type": "real",
		"searchable": false,
		"description": "Length of minor axis of elliptical fit to cavity",
		"verbose_name": "CC Minor Axis",
	},
	{
		"name": "cc_axisunit",
		"type": "text",
		"searchable": false,
		"description": "Unit of measure for major and minor axes. Typically Rsun",
		"verbose_name": "CC Axis Unit",
	},
	{
		"name": "cc_tiltanglemajorfromradial",
		"type": "real",
		"searchable": false,
		"description": "Angle between major axis and local disk-projected radial vector, measured clockwise from radial vector.",
		"verbose_name": "CC Tilt Angle Major From Radial",
	},
	{
		"name": "cc_tiltangleunit",
		"type": "text",
		"searchable": false,
		"description": "Unit of measure for CC_TiltAngleMaorFromRadial. Typicall deg.",
		"verbose_name": "CC Tilt Angle Unit",
	},
	{
		"name": "to_shape",
		"type": "text",
		"searchable": true,
		"description": "Apparent shape of topoogical object. Example values can be X-point, cusp, dome, line.",
		"verbose_name": "Topo. Shape",
	},
	{
		"name": "unsignedflux",
		"type": "real",
		"searchable": true,
		"description": "Total unsigned flux in region",
		"verbose_name": "Unsigned Flux",
	},
	{
		"name": "magfluxunit",
		"type": "text",
		"searchable": false,
		"description": "Magnetic Flux unit (e.g. 'Mx')",
		"verbose_name": "Mag Flux Unit",
	},
	{
		"name": "meaninclinationgamma",
		"type": "real",
		"searchable": true,
		"description": "Mean inclination angle (gamma) (degrees)",
		"verbose_name": "Mean Inclination Gamma",
	},
	{
		"name": "meangradienttotal",
		"type": "real",
		"searchable": true,
		"description": "Mean value of the total field gradient",
		"verbose_name": "Mean Gradient Total",
	},
	{
		"name": "meangradientvert",
		"type": "real",
		"searchable": true,
		"description": "Mean value of the vertical field gradient",
		"verbose_name": "Mean Gradient Vert.",
	},
	{
		"name": "meangradienthorz",
		"type": "real",
		"searchable": true,
		"description": "Mean value of the horizontal field gradient",
		"verbose_name": "Mean Gradient Horz.",
	},
	{
		"name": "gradientunit",
		"type": "text",
		"searchable": false,
		"description": "Gradient unit (e.g. 'G/m')",
		"verbose_name": "Gradient Unit",
	},
	{
		"name": "meanvertcurrentdensity",
		"type": "real",
		"searchable": true,
		"description": "Mean vertical current density",
		"verbose_name": "Mean Vert. Current Density",
	},
	{
		"name": "currentdensityunit",
		"type": "text",
		"searchable": false,
		"description": "Current density unit (e.g. 'mA/m^2')",
		"verbose_name": "Current Density Unit",
	},
	{
		"name": "unsignedvertcurrent",
		"type": "real",
		"searchable": false,
		"description": "Total unsigned vertical current",
		"verbose_name": "Unsigned Vert. Current",
	},
	{
		"name": "currentunit",
		"type": "text",
		"searchable": false,
		"description": "Current unit (e.g. 'A')",
		"verbose_name": "Current Unit",
	},
	{
		"name": "meantwistalpha",
		"type": "real",
		"searchable": true,
		"description": "Mean twist parameter (alpha)",
		"verbose_name": "Mean Twist Alpha",
	},
	{
		"name": "twistunit",
		"type": "text",
		"searchable": false,
		"description": "Twist unit (e.g. '1/Mm')",
		"verbose_name": "Twist Unit",
	},
	{
		"name": "meancurrenthelicity",
		"type": "real",
		"searchable": true,
		"description": "Mean current helicity",
		"verbose_name": "Mean Current Helicity",
	},
	{
		"name": "unsignedcurrenthelicity",
		"type": "real",
		"searchable": true,
		"description": "Total unsigned current helicity",
		"verbose_name": "Unsigned Current Helicity",
	},
	{
		"name": "absnetcurrenthelicity",
		"type": "real",
		"searchable": true,
		"description": "Absolute value of the net current helicity",
		"verbose_name": "Abs. Net Current Helicity",
	},
	{
		"name": "currenthelicityunit",
		"type": "text",
		"searchable": false,
		"description": "Current helicity unit (e.g. '(G^2)/m')",
		"verbose_name": "Current Helicity Unit",
	},
	{
		"name": "savncpp",
		"type": "real",
		"searchable": true,
		"description": "Sum of the Absolute Value of the Net Currents Per Polarity (SAVNCPP)",
		"verbose_name": "SAVNCPP",
	},
	{
		"name": "meanphotoenergydensity",
		"type": "real",
		"searchable": true,
		"description": "Mean photospheric excess magnetic energy density",
		"verbose_name": "Mean Photo. Energy Density",
	},
	{
		"name": "meanenergydensityunit",
		"type": "text",
		"searchable": false,
		"description": "Energy Density unit (e.g. 'erg/(cm^3)')",
		"verbose_name": "Mean Energy Density Unit",
	},
	{
		"name": "totalphotoenergydensity",
		"type": "real",
		"searchable": true,
		"description": "Total photospheric magnetic energy density (TOTPOT in SHARP)",
		"verbose_name": "Total Photo. Energy Density",
	},
	{
		"name": "totalenergydensityunit",
		"type": "text",
		"searchable": false,
		"description": "Energy/length unit (e.g. 'erg/cm')",
		"verbose_name": "Total Energy Density Unit",
	},
	{
		"name": "totalphotoenergy",
		"type": "real",
		"searchable": true,
		"description": "Total photospheric magnetic energy (TOTPOT in SHARP times pixel width)",
		"verbose_name": "Total Photo. Energy",
	},
	{
		"name": "totalphotoenergyunit",
		"type": "text",
		"searchable": false,
		"description": "Energy unit (e.g. 'erg')",
		"verbose_name": "Total Photo. Energy Unit",
	},
	{
		"name": "meanshearangle",
		"type": "real",
		"searchable": true,
		"description": "Mean shear angle for B_total (degrees)",
		"verbose_name": "Mean Shear Angle",
	},
	{
		"name": "highshearareapercent",
		"type": "real",
		"searchable": true,
		"description": "Area with shear angle greater than 45 as a percent of total area",
		"verbose_name": "High Shear Area Percent",
	},
	{
		"name": "highsheararea",
		"type": "real",
		"searchable": true,
		"description": "Area with shear angle greater than 45 as a percent of total area",
		"verbose_name": "High Shear Area",
	},
	{
		"name": "highshearareaunit",
		"type": "text",
		"searchable": false,
		"description": "Area unit (e.g. 'm^2')",
		"verbose_name": "High Shear Area Unit",
	},
	{
		"name": "log_r_value",
		"type": "real",
		"searchable": false,
		"description": "Log (Unsigned Flux R) (prelog value in Gauss*MDI-pixels - Schrijver 2007)",
		"verbose_name": "Log R Value",
	},
	{
		"name": "gwill",
		"type": "real",
		"searchable": true,
		"description": "Gradient-weighted inversion-line length (Mason & Hoeksema 2010)",
		"verbose_name": "GWILL",
	},
	{
		"name": "gwillunit",
		"type": "text",
		"searchable": false,
		"description": "GWILL (length) unit (e.g. 'Mm')",
		"verbose_name": "GWILL Unit",
	},
	{
		"name": "ar_axislength",
		"type": "real",
		"searchable": true,
		"description": "Axis length (bipole separation distance)",
		"verbose_name": "AR Axis Length",
	},
	{
		"name": "ar_lengthunit",
		"type": "text",
		"searchable": false,
		"description": "Units for AR_AxisLength and AR_NeutralLength",
		"verbose_name": "AR Length Unit",
	},
	{
		"name": "ar_sumpossignedflux",
		"type": "real",
		"searchable": true,
		"description": "Total positive signed flux",
		"verbose_name": "AR Sum Pos. Signed Flux",
	},
	{
		"name": "ar_sumnegsignedflux",
		"type": "real",
		"searchable": true,
		"description": "Total negative signed flux (negative number)",
		"verbose_name": "AR Sum Neg. Signed Flux",
	},
	{
		"name": "ar_neutrallength",
		"type": "real",
		"searchable": true,
		"description": "The total length of polarity separation line segments within the AR",
		"verbose_name": "AR Neutral Length",
	},
	{
		"name": "ar_pilcurvature",
		"type": "real",
		"searchable": true,
		"description": "Dimensionless curvature of main PIL (PIL length / direct distance between endpoints)",
		"verbose_name": "AR PIL Curvature",
	},
])
